export const MCQ_GENERATION_CONSTRAINTS = {
  MIN_WORD_COUNT_FOR_CONTENT_SLIDE: 15,
  IMPORTANCE_WEIGHTS: {
    tfidf: 0.30,
    heading: 0.25,
    crossSlideFreq: 0.25,
    aiSalience: 0.20
  },
  FOCUS_KEYWORD_THRESHOLD: 0.55,
  FOCUS_KEYWORD_MAX_COUNT: 15,
  MAX_QUESTIONS_PER_SLIDE_MULTIPLIER: 2, // MAX_PER_SLIDE = ceil(M/N) * 2
  COVERAGE_TARGET: 0.80,
  GROUNDING_THRESHOLD: 0.72,
  DUPLICATE_THRESHOLD: 0.90,
  ANSWER_KEY_MAX_DEVIATION_RATIO: 0.40,
  DIFFICULTY_BALANCE_TOLERANCE: 0.15,
  MAX_ADDITIONAL_QUESTIONS_RATIO: 0.20,
  DISTRACTOR_LENGTH_VARIANCE_MAX: 0.40,
  AI_SALIENCE_MODEL_TIER: 'fast', // Used as a hint
} as const;
